# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     io.kompose.service: penpot-minio
#   name: penpot-minio
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
