apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mccaf\go\bin\kompose.exe convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: penpot-postgres
  name: penpot-postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: penpot-postgres
