apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "penpot.fullname" . }}-assets
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
