apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: penpot-redis
  name: penpot-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: penpot-redis
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\mccaf\go\bin\kompose.exe convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: penpot-redis
    spec:
      automountServiceAccountToken: false
      containers:
        - name: penpot-redis
          image: redis:7
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 2Gi
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
