apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: penpot-redis
  name: penpot-redis
spec:
  ports:
    - name: "default"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: penpot-redis
