apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mccaf\go\bin\kompose.exe convert
    kompose.version: 1.34.0 (HEAD)
    traefik.enable: "false"
  labels:
    io.kompose.service: penpot-frontend
  name: penpot-frontend
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 80
  selector:
    io.kompose.service: penpot-frontend
